services:
  sonic-odyssey-test-db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: testdb
    ports:
      - "54320:5432"
    volumes:
      - ./../../../../../../sonic-odyssey-test-data:/var/lib/postgresql/data

volumes:
  sonic-odyssey-test-data:

networks:
  default:
    name: sonic-odyssey-network