// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailHasher is an autogenerated mock type for the EmailHasher type
type EmailHasher struct {
	mock.Mock
}

// HashEmail provides a mock function with given fields: email
func (_m *EmailHasher) HashEmail(email string) string {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for HashEmail")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewEmailHasher creates a new instance of EmailHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailHasher {
	mock := &EmailHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
