definitions:
  v1.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  v1.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      nickname:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - nickname
    - password
    type: object
  v1.SignUpResponse:
    properties:
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: User SignUp
      parameters:
      - description: SignUp Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: User SignUp
      tags:
      - User
swagger: "2.0"
